"""
DOLPHYN: Decision Optimization for Low-carbon Power and Hydrogen Networks
Copyright (C) 2022,  Massachusetts Institute of Technology
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
A complete copy of the GNU General Public License v2 (GPLv2) is available
in LICENSE.txt.  Users uncompressing this from an archive may not have
received this license file.  If not, see <http://www.gnu.org/licenses/>.
"""

@doc raw"""
	write_power_plant_emissions(path::AbstractString, sep::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for reporting the different values of power generated by the different technologies in operation.
"""
function write_power_plant_emissions(path::AbstractString, sep::AbstractString, inputs::Dict, setup::Dict, EP::Model)
	dfGen = inputs["dfGen"]
	G = inputs["G"]     # Number of resources (generators, storage, DR, and DERs)
	T = inputs["T"]     # Number of time steps (hours)

	# Power injected by each resource in each time step
	dfPower_Plant_Emissions = DataFrame(Resource = inputs["RESOURCES"], Zone = dfGen[!,:Zone], AnnualSum = Array{Union{Missing,Float32}}(undef, G))
	if setup["ParameterScale"] ==1
		for i in 1:G
			dfPower_Plant_Emissions[!,:AnnualSum][i] = sum(inputs["omega"].* (value.(EP[:eEmissionsByPlant])[i,:])) * ModelScalingFactor
		end
		dfPower_Plant_Emissions = hcat(dfPower_Plant_Emissions, DataFrame((value.(EP[:eEmissionsByPlant]))* ModelScalingFactor, :auto))
	else
		for i in 1:G
			dfPower_Plant_Emissions[!,:AnnualSum][i] = sum(inputs["omega"].* (value.(EP[:eEmissionsByPlant])[i,:]))
		end
		dfPower_Plant_Emissions = hcat(dfPower_Plant_Emissions, DataFrame(value.(EP[:eEmissionsByPlant]), :auto))
	end

	auxNew_Names=[Symbol("Resource");Symbol("Zone");Symbol("AnnualSum");[Symbol("t$t") for t in 1:T]]
	rename!(dfPower_Plant_Emissions,auxNew_Names)



	total = DataFrame(["Total" 0 sum(dfPower_Plant_Emissions[!,:AnnualSum]) fill(0.0, (1,T))], :auto)
	for t in 1:T
		if v"1.3" <= VERSION < v"1.4"
			total[!,t+3] .= sum(dfPower_Plant_Emissions[!,Symbol("t$t")][1:G])
		elseif v"1.4" <= VERSION < v"1.9"
			total[:,t+3] .= sum(dfPower_Plant_Emissions[:,Symbol("t$t")][1:G])
		end
	end
	rename!(total,auxNew_Names)

	dfPower_Plant_Emissions = vcat(dfPower_Plant_Emissions, total)
 	CSV.write(string(path,sep,"power_plant_emissions.csv"), dftranspose(dfPower_Plant_Emissions, false), writeheader=false)

	return dfPower_Plant_Emissions
end
