"""
CaptureX: An Configurable Capacity Expansion Model
Copyright (C) 2021,  Massachusetts Institute of Technology
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Captureeral Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Captureeral Public License for more details.
A complete copy of the GNU Captureeral Public License v2 (GPLv2) is available
in LICENSE.txt.  Users uncompressing this from an archive may not have
received this license file.  If not, see <http://www.gnu.org/licenses/>.
"""

@doc raw"""
	write_power(path::AbstractString, sep::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_co2_capture_compression_plant(path::AbstractString, sep::AbstractString, inputs::Dict, setup::Dict, EP::Model)
	dfCO2CaptureComp = inputs["dfCO2CaptureComp"]
	H = inputs["CO2_CAPTURE_COMP_ALL"]     # Number of resources (Capture units, storage, DR, and DERs)
	T = inputs["T"]     # Number of time steps (hours)

	# Power injected by each resource in each time step
	# dfCO2CaptureCompOut_annual = DataFrame(Resource = inputs["CO2_CAPTURE_COMP_NAME"], Zone = dfCO2CaptureComp[!,:Zone], AnnualSum = Array{Union{Missing,Float32}}(undef, H))
	dfCO2CaptureCompOut = DataFrame(Resource = inputs["CO2_CAPTURE_COMP_NAME"], Zone = dfCO2CaptureComp[!,:Zone], AnnualSum = Array{Union{Missing,Float32}}(undef, H))

	
	for i in 1:H
		if setup["ParameterScale"]==1
			dfCO2CaptureCompOut[!,:AnnualSum][i] = sum(inputs["omega"].* (value.(EP[:vCO2_Capture_Compressed])[i,:])*ModelScalingFactor)
		else
			dfCO2CaptureCompOut[!,:AnnualSum][i] = sum(inputs["omega"].* (value.(EP[:vCO2_Capture_Compressed])[i,:]))
		end
	end

	# Load hourly values
	if setup["ParameterScale"]==1
		dfCO2CaptureCompOut = hcat(dfCO2CaptureCompOut, DataFrame((value.(EP[:vCO2_Capture_Compressed]))*ModelScalingFactor, :auto))
	else
		dfCO2CaptureCompOut = hcat(dfCO2CaptureCompOut, DataFrame((value.(EP[:vCO2_Capture_Compressed])), :auto))
	end

	# Add labels
	auxNew_Names=[Symbol("Resource");Symbol("Zone");Symbol("AnnualSum");[Symbol("t$t") for t in 1:T]]
	rename!(dfCO2CaptureCompOut,auxNew_Names)

	total = DataFrame(["Total" 0 sum(dfCO2CaptureCompOut[!,:AnnualSum]) fill(0.0, (1,T))], :auto)

	for t in  1:T
		total[:,t+3] .= sum(dfCO2CaptureCompOut[:,Symbol("t$t")][1:H])
	end

	rename!(total,auxNew_Names)
	dfPower = vcat(dfCO2CaptureCompOut, total)

 	CSV.write(string(path,sep,"CSC_co2_capture_compression_plant.csv"), dftranspose(dfCO2CaptureCompOut, false), writeheader=false)
	return dfCO2CaptureCompOut


end
