"""
DOLPHYN: Decision Optimization for Low-carbon Power and Hydrogen Networks
Copyright (C) 2021,  Massachusetts Institute of Technology
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
A complete copy of the GNU General Public License v2 (GPLv2) is available
in LICENSE.txt.  Users uncompressing this from an archive may not have
received this license file.  If not, see <http://www.gnu.org/licenses/>.
"""

@doc raw"""
	write_h2_gen(path::AbstractString, setup::Dict, inputs::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_syn_gen(path::AbstractString, setup::Dict, inputs::Dict, EP::Model)

	dfSynGen = inputs["dfSynGen"]
	H = inputs["SYN_RES_ALL"]     # Number of resources (generators, storage, DR, and DERs)
	T = inputs["T"]     # Number of time steps (hours)

	# Power injected by each resource in each time step
	# dfSynGenOut_annual = DataFrame(Resource = inputs["H2_RESOURCES_NAME"], Zone = dfSynGen[!,:Zone], AnnualSum = Array{Union{Missing,Float32}}(undef, H))
	dfSynGenOut = DataFrame(Resource = inputs["SYN_RESOURCES_NAME"], Zone = dfSynGen[!,:Zone], AnnualSum = Array{Union{Missing,Float32}}(undef, H))

	for i in 1:H
		dfSynGenOut[!,:AnnualSum][i] = sum(inputs["omega"].* (value.(EP[:vSynGen])[i,:]))
	end
	# Load hourly values
	dfSynGenOut = hcat(dfSynGenOut, DataFrame((value.(EP[:vSynGen])), :auto))

	# Add labels
	auxNew_Names=[Symbol("Resource");Symbol("Zone");Symbol("AnnualSum");[Symbol("t$t") for t in 1:T]]
	rename!(dfSynGenOut,auxNew_Names)

	total = DataFrame(["Total" 0 sum(dfSynGenOut[!,:AnnualSum]) fill(0.0, (1,T))], :auto)

	for t in  1:T
		total[:,t+3] .= sum(dfSynGenOut[:,Symbol("t$t")][1:H])
	end

	rename!(total,auxNew_Names)
	dfSynGenOut = vcat(dfSynGenOut, total)

 	CSV.write(joinpath(path, "Syn_fuels_generation_discharge.csv"), dftranspose(dfSynGenOut, false), writeheader=false)

	return dfSynGenOut
end
